image: Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov
- choco install dotnet-sdk

build:
  project: Kookie.sln
  verbosity: minimal

test_script:
- dotnet tool install --global coverlet.console --verbosity q
- cd C:\projects\Kookie\Kookie.Tests
- dotnet test --collect:"XPlat Code Coverage" --settings coverage.settings --verbosity n
- pwd
- cd "TestResults/"
- for /d %%A in (*) do cd %%A
- pwd
- dir
- move coverage.opencover.xml C:\projects\Kookie\Kookie_coverage.xml
- codecov -f "C:\projects\Kookie\Kookie_coverage.xml" -t ${{ secrets.CODECOV_TOKEN }}
- curl -s https://codecov.io/bash > codecov
- chmod +x codecov
