# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  tests: './Kookie.Tests/Kookie.Tests.csproj'

steps:
- script: dotnet tool install --global coverlet.console
  displayName: 'dotnet tool install coverlet.console'
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test $(tests) --collect:"XPlat Code Coverage"
  displayName: 'dotnet test'
- script: | 
    cd Kookie.Tests/TestResults
    cd */
    codecov -f coverage.opencover.xml -t $(CODECOV_TOKEN)
  displayName: 'codecov -f coverage.opencover.xml'