# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  tests: './Kookie.Tests/Kookie.Tests.csproj'
  coverage: "./test/Kookie.Tests/coverage.opencover.xml"

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet tool install --global Codecov.Tool
  displayName: 'dotnet tool install Codecov.Tool'
- script: dotnet test $(tests) -c Debug /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  displayName: 'dotnet test'
- script: codecov -f $(coverage) -t $(CODECOV_TOKEN)
  displayName: 'codecov -f $(coverage)'